version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - app-network

  mongodb-seed:
    build: ./mongodb
    container_name: mongo-seed
    depends_on:
      - mongodb
    command: mongoimport --host mongodb --collection user --type json --file /init.json --jsonArray
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
